name: pingpong flutter
description: bom jogo

dependencies:
  flutter:
  sdk: flutter
  provider: ^6.2.1
  dio: ^4.0.0
  shared_preferences: ^2.0.10 
  get: ^4.3.8 
  firebase_core: ^1.10.6 
  firebase_auth: ^4.5.0 
  firebase_database: ^7.3.0 
  http: ^0.13.3
  equatable: ^2.0.2 
  bloc: ^7.3.1
  flutter_bloc: ^7.3.1
  form_bloc: ^0.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
